title: Onyedikachi Nwano
logo: kachi.png
description: Highly skilled Data Analyst with experience using data analystic tools such as Microsoft Excel, SQL, Power BI
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
